[#45] git pre-commit hook checkstyle 적용하기
f-lab-edu/DeliDeli pull request #46
Opened 2022-02-23 12:01 UTC by jeongeun1127

2022-02-25 03:29 UTC, f-lab-dev approved these changes

2022-02-25 03:29 UTC, f-lab-dev commented
아 프로젝트 처음 clone 받은 사람이 설정할 수 있도록 명령어 가이드도 들어가있으면 좋을 것 같습니다~

2022-02-25 10:31 UTC, jeongeun1127 commented
수연 님도 참고하실 수 있도록 가이드 작성하겠습니다!

2022-02-26 16:17 UTC, Yeon-Nexus commented
> * 해당 파일이 없이 다른 브랜치에서 작업하면 `commit`이 되지 않아서 본 브랜치를 베이스로 `feature38` 브랜치를 만들게 되었습니다.

설명해주신 부분이 어떤 부분인지 조금 이해가 되지않습니다!! 혹시 설명해주실 수 있으실까요?

2022-02-27 01:39 UTC, jeongeun1127 commented
>

2022-02-27 01:53 UTC, jeongeun1127 commented
> > * 해당 파일이 없이 다른 브랜치에서 작업하면 `commit`이 되지 않아서 본 브랜치를 베이스로 `feature38` 브랜치를 만들게 되었습니다.
> 
> 설명해주신 부분이 어떤 부분인지 조금 이해가 되지않습니다!! 혹시 설명해주실 수 있으실까요?

git hook pre-commit의 checkstyle 검사에 필요한 naver-checkstyle-rules.xml 파일을 이 작업 브랜치에만 추가했습니다. 다른 브랜치(develop 베이스였던)에는 해당 파일이 없기 때문에, checkstyle 검사를 위한 파일이 존재하지 않는다는 문구와 함께 커밋이 되지 않습니다. 그래서 이 작업 브랜치를 베이스로 feature38 브랜치를 만들어 git hook pre-commit이 해당 파일로 checkstyle을 검사할 수 있도록 만들어주었습니다~

2022-02-27 14:08 UTC, f-lab-dev requested changes

2022-02-27 14:08 UTC, f-lab-dev commented on src/main/resources/checkstyle/checkstyle-guide
> +git hook pre-commit에 naver-checkstyle-rule.xml 적용하기
이런 문서는 마크다운으로 작성해보시면 어떨까요?

2022-02-28 05:54 UTC, jeongeun1127 commented on src/main/resources/checkstyle/checkstyle-guide
> +git hook pre-commit에 naver-checkstyle-rule.xml 적용하기
넵 마크다운 활용하여 작성해보겠습니다!

2022-02-28 09:05 UTC, jeongeun1127 commented
인텔리제이에서 마크다운을 플러그인 하여 작업 내용을 preview하며 작업하였습니다.

2022-02-28 09:17 UTC, f-lab-dev approved these changes
👍

2022-02-28 09:54 UTC, merged